//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Competitions.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zawody
    {
        public int ID { get; set; }
        public int ID_uzytkownik { get; set; }
        public int ID_bieg { get; set; }
        public int Numer { get; set; }
    
        public virtual Bieg Bieg { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
